//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtHistory.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArtHistoryDBEntities : DbContext
    {
        public ArtHistoryDBEntities()
            : base("name=ArtHistoryDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TbEpohi> TbEpohi { get; set; }
        public virtual DbSet<TbHudozhniki> TbHudozhniki { get; set; }
        public virtual DbSet<TbKartini> TbKartini { get; set; }
        public virtual DbSet<TbSlovar> TbSlovar { get; set; }
        public virtual DbSet<TbSsilki> TbSsilki { get; set; }
        public object Items { get; internal set; }
    }
}
