//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtHistory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbEpohi
    {
        public int Id { get; set; }
        public string Nazvanie { get; set; }
        public string Opisanie { get; set; }
        public string Date { get; set; }
        public string ImagePath { get; set; }
        public bool Favorite { get; set; }
    }
}
